""" Importing Hydrodynamic Coefficients

This example demonstrates how to use SIMA along with simapy to import hydrodynamic
coefficients from datasets generated by WAMIT. The same approach can be used to import
data from HydroD/WADAM or any other file format which is supported by SIMA.

Before running the example script, make sure that you have an environmental variable
SRE_EXE which points to the sre executable of SIMA.

This example requires SIMA version 4.4.0 or later.
"""
import os
import shutil
from pathlib import Path

from simapy.sre import SIMA
from simapy.sima_reader import SIMAReader
from simapy.sima_writer import SIMAWriter

from simapy.sima.command import ImportCommand, ExportCommand, Command

SCRIPT_DIR = Path(os.path.realpath(os.path.dirname(__file__)))


def main():
    """
    Import hydrodynamic coefficients from WAMIT dataset using SRE and export to JSON file.
    """
    # Here we use the import_file function defined below to import data from the WAMIT
    # dataset by pointing at the .out-file. The same function could be used to for
    # example to import a G1.SIF file created by HydroD/WADAM as well.
    # The function returns a list of tasks because certain file formats (e.g. stasks)
    # might contain multiple tasks. WAMIT result files only create a single task
    # hence the variable is assigned to the zeroth element of the list.

    workspace = Path("output/simo/simo_wamit_import")
    if workspace.exists():
        shutil.rmtree(workspace, ignore_errors=True)
    os.makedirs(workspace)

    task = import_file(workspace, SCRIPT_DIR / "wamit_data" / "sima.out")[0]

    # After the task has been imported we could do some manipulations to it, add more
    # data and perhaps make SIMA run a simulation with the task. For this example we
    # just export it to a JSON file called imported.json. This file can be imported
    # into SIMA in order to inspect the results.
    file = workspace / "simo_wamit_import.json"
    os.makedirs(file.parent, exist_ok=True)
    SIMAWriter().write([task], file)


def import_file(workspace: Path, filename: Path):
    """Import a file of a type supported by SIMA as a list of tasks.

    The function uses an environmental variable SRE_EXE to locate the SIMA installation,
    make sure it is set before running.
    """
    out_file = workspace / "out.json"

    # Run SIMA to import SIF file and export JSON
    import_command = ImportCommand(file=str(filename))
    export_command = ExportCommand(file=str(out_file), delete=True)
    commands = [import_command, export_command]

    run_sima(workspace, commands)

    # Import JSON file exported by SIMA
    return SIMAReader().read(out_file)


def run_sima(workspace: Path, commands: list[Command]):
    """Run SIMA with the given workspace directory and command line arguments.

    The function uses an environmental variable SRE_EXE to locate the SIMA installation,
    make sure it is set before running.
    """
    sima = SIMA()
    sima.run(workspace, commands)


if __name__ == "__main__":
    main()
