name: Documentation

on: [push]

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    # Permissions needed for GitHub Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Build documentation
        run: |
          cd docs
          python -m sphinx -b html . _build/html
      
      # Upload standard artifact for normal workflows
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-${{ github.ref_name }}
          path: docs/_build/html
          retention-days: 1
          
      # Deploy to GitHub Pages only on main branch
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4

